modLoader = "javafml"
loaderVersion = "[36,)"
license = "LGPL-3.0-only"

[[mods]]
modId = "jta"
version = "1.0.0-alpha.4"
displayName = "Jesse's Transit Addon"
authors = ["AwesomeKalin55", "Jesse"]
description = "Jesse's Transit Addon (JTA) is a collection of decorative and functional blocks for use with the MTR mod"
logoFile = "icon.png"

[[dependencies.jta]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.jta]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.jta]]
modId = "mtr"
mandatory = true
versionRange = "[4.0.0-beta-8,4.1)"
ordering = "AFTER"
side = "BOTH"
